name: Create Repository

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      repository_suffix:
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      # GitHub CLI 인증
      - name: Login to GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      # 저장소 생성 단계
      - name: Create repository
        run: |
          gh repo create ARUM-MED-SOURCE/${{ inputs.repository_name }}-${{ inputs.repository_suffix }} --public --add-readme
